config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users
  resources :sessions
  resources :gossips

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

=begin

get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


=end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 helper_method :current_user
	 
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


	def index
		@gossips = Gossip.all
	end

	def new
		@gossip = Gossip.new
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		respond_to do |format|
      		if @gossip.update(gossip_params)
        		format.html { redirect_to gossip_path(@gossip), notice: 'Gossip was successfully updated.' }
      		end
  		end
	end

	def create

		@gossip = Gossip.new(gossip_params)
		respond_to do |format|	
			if @gossip.save
				format.html { redirect_to gossip_path(@gossip), notice: 'Gossip was successfully updated.' }
			end
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		if @gossip.present?
			@gossip.destroy
		respond_to do |format|
			format.html { redirect_to "/" , notice: 'Gossip has been destroyed!' }
			end
		end
	end


	private
    # Use callbacks to share common setup or constraints between actions.
    	def set_gossip
      		@gossip = Gossip.find(params[:id])
    	end

    # Never trust parameters from the scary internet, only allow the white list through.
    	def gossip_params
    		#je push le user id dans mon hash
      		temp_params = params.require(:gossip).permit(:anonymous_author, :content, :user_id)
      		temp_params.merge!(user_id: session[:user_id])
      		return temp_params
    	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @gossips = Gossip.all
    print @gossips
  end

  # GET /users/1
  # GET /users/1.json
  def show
    print @gossips
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    puts "coucou"
    print @gossips
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip) do |form| %>

<div style="text-align: center;">
  <form action="/gossips/new">
    <div class="form-group">
      <%= form.text_field :anonymous_author, placeholder:"Auteur Anonyme", label: "Auteur anonyme", label_class:"form_label" %>
    </div>

    <div class="field">
      <%= form.text_field :content, placeholder:"Idea", label: "Idea", label_class:"form_label" %>
    </div>
	<% user_id = session[:user_id] %>
      <%= form.button :submit, class:"bg-warning btn btn-treehouse" %>
  </form>
</div>
<% end %>

app/views/gossips/edit.html.erb
<br>
<h1 style="text-align: center;">Editing User</h1>
<br>

<div style="margin: 0 auto; width: 50%;">
<div style="text-align: center;" class="card">
  <div "text-align: center;" class="card-header">
<%= render 'form', gossip: @gossip %>
	<br>
	
	<div class ="bg-primary bg-warning btn btn-primary">
		<%= link_to 'Back', gossip_path %>
	</div>
	<div class ="bg-primary bg-warning btn btn-primary">
 <%= link_to 'Destroy', gossip_path, method: :delete %> 


	</div>
</div>
</div>
</div>

app/views/gossips/new.html.erb
New idea

<%= render 'form', gossip: @gossip %>

app/views/gossips/show.html.erb
<br>
<div style="text-align: center; font-size: 20px; margin: 0 auto; width: 50%;">
	<div class="card">
	  	<div class="card-header">
			<div class="card-body">
				<p class="card-text">
	  				<strong>Username:</strong>
					<%= @gossip.anonymous_author %>
				</p>

				<p class="card-text">
					<strong>Content:</strong>
					<%= @gossip.content %>
				</p>
			</div>
			  <%= link_to 'Edit', edit_gossip_path(@gossip)%>
	   </div>
	</div>
</div>
<br>

app/views/home/index.html.erb
<div class="container-cent">
	<h1 class="main-title">TheFacebookProject </h1>
</div>
<% if current_user %>
  	<h4 class="main-title">Connecté en tant que  <strong><%= current_user.email %>.</strong>
  	<%= link_to "Déconnexion", session_url(current_user), method: :delete, class: "btn btn-primary" %></h4>
<% else %>
<h4 class="main-title"><i class="em em-arrow_double_down"></i> Pour utiliser The Facebook vous devez vous <strong>Connecter</strong> ou bien vous <strong>Inscrire</strong> <i class="em em-arrow_double_down"></i><h4>
	<%=  link_to "Inscription", new_user_url , class: "btn btn-success", id:"ins" %>  
	<%=  link_to "Connexion", new_session_url , class: "btn btn-success ", id: "con" %> 
<% end %>
<p style="color: green" id="notice"><%= notice %></p>

<% Gossip.all.each do |gossip| %>
<div>
<div class="card" style="text-align: center; margin: 0 auto; width: 50%;">
  	<div class="card-header">
    	Gossip <%= gossip.id %>
  	</div>
  <div class="card-body">
    	<p class="card-text"><%= gossip.anonymous_author %></p>
    	<p class="card-text text"><%= gossip.content %></p>
  	</div>
  <%= link_to 'Show', gossip %>
	</div>
</div>
<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Facebook</title>
    <%= favicon_link_tag asset_path('2000px-F_icon.svg.png') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="header">
    <div class="header-container">
        <h1 class="header-title"><a href="/">The Facebook</a></h1>
        <div class="header-link">
          <a class="header-link" href="/sessions/new">Connexion <i class="fas fa-align-right"></i></a>
          <a class="header-link" href="/users/new">Inscription <i class="fas fa-book"></i></a>
          <a class="header-link" href="/gossips/new">Nouveau Post</a>
          <a class="header-link" href="/">Home <i class="fas fa-home"></i></a>
        </div>
    </div>
  </div>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <div class="footer">
    <div class="footer-container">
    <div class="footer-heart-container">
      <p class="footer-heart">Made with  <i id="heart" class="em em-heart"></i>  in Strasbourg</p>
    </div>
  </div>
</div>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>